title: 'Starscream33.github.io'
description: "."
baseurl: "/home"
url: "https://Starscream33.github.io"

header_pages:
  - home.md
  - research.md
  - BJJ.md
  - Climbing
  - Personal Projects

style: dark

footer: ''

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
